_BASE_: "Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (15000, 30000)
  MAX_ITER: 22000
OUTPUT_DIR: "output/SOLOv2/r101_3x_20000"